# vertex.capnp
@0xa44060d6b7781c9a;
# ID generated by 'capnp id'

struct Vertex {
  id @0 :UInt32;
  lonDeg @1:Float32;
  latDeg @2:Float32;

  union {
    elevMeters @3 :Float32;
    elevNone @4 :Void;
    }         

}