# vertex.capnp
@0xa44060d6b7781c9a;
# ID generated by 'capnp id'

# Vertex Descriptor, enough to uniquely identify a vertex
struct VertDesc { 
  id @0 :UInt64;
  source @1 :Source;

  enum Source {
    osm @0;
    natEarth @1;
    tilePoly @2;
    roadWaypoint @3;
  }
}

struct Vertex {
  desc @0 :VertDesc;
    
  lonDeg @1:Float32;
  latDeg @2:Float32;

  union {
    elevMeters @3 :Float32;
    elevNone @4 :Void;
  }         
}